### ISSUE TITLE
NoClassDefFoundError when using Element

### ISSUE THREAD

**Issue by DatPenguin** [SimonFlash/TeslaPowered#13]
Hi !

I wanted to use the TeslaLibs to create a GUI which included Element vars.

When I try to open the GUI, I get the following error : 
```
[09:55:10] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'checkranks' for source EntityPlayerMP['AlcaTorda'/78, l='world', x=-965,82, y=72,98, z=513,99]: com/mcsimonflash/sponge/teslalibs/inventory/Element
java.lang.NoClassDefFoundError: com/mcsimonflash/sponge/teslalibs/inventory/Element
        at sykoure.ranks.gui.CheckRanksGui.<clinit>(CheckRanksGui.java:20) ~[CheckRanksGui.class:?]
        at sykoure.ranks.commands.CheckRanks.execute(CheckRanks.java:25) ~[CheckRanks.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-3361]
```

I include TeslaLibs with gradle with jitpack.io .

Is there a fix to this problem ?

Thank you

**Comment by CraftSteamG** [comment]
Share your build.gradle, to make sure you're actually shading it.

**Comment by SimonFlash** [comment]
Ah, just got a notification for this. @CraftSteamG is correct - you need to either shade TeslaLibs into your plugin (and also relocate it into your own package) or depend on TeslaLibs at runtime, which would require TeslaPowered to be installed. The [Developer API](https://ore.spongepowered.org/Simon_Flash/TeslaPowered/pages/Developer-API) page on the docs explains how to do this and which method you should use.

In the future, GitHub should be used for issues - not support. Please use my [suppord discord](https://discord.gg/4wayq37) for any further questions about using TeslaLibs.
